---
_extends: .github

repository:
  name: hs-msgpack-rpc-conduit
  description: A MessagePack RPC implementation in Haskell
  topics: msgpack, rpc, protocol, network

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - Travis CI - Pull Request
          - code-review/reviewable
          - coverage/coveralls
