---
language: generic
dist: xenial
os: linux

env:
  global:
    # HACKAGE_USERNAME=[secure]
    - secure: "DXnlBg5xxaXUc0+zvR3bWBZPdllHBLTzSmdZ7dXAiQppAk3Frv+k33b4mJhqvebvYlallB+ZYPNpvv5LJfn7PSlPyq0Vg/jn4tswr1foc2vbQr0U+zDOXLaIlOpDwceZiMeDVBaML1kAdYha4jWgMUoxBx+QFdlp7OZI30Ss//eisbQIrndhFjd4MmeWiiQFmL5SC5mf63xpspV6YLkqHRddC21xgR6YnWrSE6pzRf6v4lRiYj4MlsA/ADlaGa25u/rYvxcg9IXnthF+7DcG4hb/AOBWmMkPBGKhv3lVe2M9cgA57te8jQsv9IGVAca+U9z9wxvdIiXSyqkR15mV0VCMXzfH9xSZHdcLxxW7V9TczCmdf0boTd+ahVn2q+TOfSLKFyYanidB8gxWxoeLY0ba1HeiazsASCeMgWz9yhQyMN9wui1OfnmSo7IFG3cmCfQG5gd/LQGcTJgLtLvrzhDxNc+vrimEP+a+bLEOJ2w4fU0dQrx8vYuzkjHi48o4WhQA7c2m8Qww27YKtBiR6dstw7wTh0SVR91OeDQTk/pVAfNwcsBGPGsac/k0rGGeqK/SpAh6LDL/8daEavc+lYB2FtLolAq1Bg5Tkw47uaS+GAspsPx9bfTB1IRGuSQNrWPuCOylMdeX5SpYkmRdMw1LJBgW6tzgodK8+TXYQd4="
    # HACKAGE_PASSWORD=[secure]
    - secure: "JDHHQhgYlQldCfS2aAmresi1wcfgFAobSHXG4QrcOiaIz3d12p4ybccgY31CE52dWTWwKdWXD+3pCVKRwUbEwj1FXvOTYn12E1ykZaewuo/10j6Nnjqa0LUUC/XmGgnDmpIEX8vs0xwgpeFUQmQQUT27G3eeBkPrdLbAW2wfXV52QXzrrajy7Q4F27h8i0GcKUFyLij0V/jOya5zuJddxcCviM383KN0e0RTk4L4HMKc905aPy+2p4fiPGIrthWkdvUZlbcPWLpSTIk5ElcMU3N3gOfncUpLWj9hzubLLVUa0SHa3yu1UvVoDZhJdHRzCt+oeceYOtfhZ1CMO9r9z2QgCsIrd+mRCroIsG/OOTC0dwxN726EAXM1beK7ev3mGWluwEbvPvbKv9Le/FXSIi6N+l9ER9oteh+prRDXNyeHb07FV8Sd+55Js3zQw6dz0fNx5zLLhT1aTQt9JhwQlZ1fRoSwTZTFubFYVGvYJVQiNqFZhCa94CeWiPoAgSCe/OTHZMf0/jPFgCPl4/RM5OaUXkd4mceO4XXZGn+HYP2duInWBg2uI0o8MUQwdObkbpr+0ZxoIxio58Ic/NWunRNcvfG4I+U0NNBgwrP24Xanr09jQO89tdFKCX1iIGmsSt1ka+oIEI81vr/PGHuoU3Qe5m5f8UhkoPclMuDzG4M="

cache:
  directories:
    - $HOME/.stack

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://github.com/TokTok/hs-tools/releases/download/v0.6/hs-tools-v0.6.tar.gz | tar xz -C $HOME

script:
  - hlint .
  - stylish-haskell-lhs -i .
  - git diff --exit-code
  - stack --no-terminal test --coverage
  - shc msgpack-rpc-conduit testsuite
  - stack sdist --tar-dir .

deploy:
  provider: releases
  token:
    secure: "tBnLJar+vXhTgYW5/Euqe27vGvefC6HX8pPegNjUdyxQA1WFoMz4J78hfR3xQe0e76CXj/Rdk3kwbc+mqeWgIj2r/bxCSSQ3GuXCQw842NEohpQT0xKG60hsti6X2mcN6prrJ4OLaAjo1Nl54LLe6d7WJbnMqG4omVtBPq/LWE53e7SIOv78WdMGu8UI7kYbzl+NMDhSgA4ODjRIc9bFpqd6eReIkPUfRDQRSIKWQz3ifWtiuDOEZkWymkX/9hEii+rNMnkkEBShqs06QFZmffHgRp0b/rYd+EOgpvDDMhtdQDTK6RyjYn12mQHJN0Vlfw/5tkaMv7CFcKbxKN5V/Spf7h6h7yOJMLyKhZCL4NCEhFQHbQr1vy1VQy81AnEZZtVWc0yfjc8iq+W8oJnt+bGn3SFnYrntZomVwj+/+9cOYknoqY6OB9IVnEUwKfdXNLrdy6fttBXzIhhYzmdARChglW/s8CRqGjspzZ5Dn+FzZdehYDeW/of8eBfMfhRZ+wfNswAbxU/JOSzNOk4yMidmoY2W2jBhY1YV7tNVDInuuGuLuiZxzrWmC3/6+qwPGYud2WWN0Xu01Qf7/PzXkgvdJRK1dhMZl/t/pfkcbbAUPeyVgEu5LfDcsnJOmCCUJ0FqWEk5dCQOGQ2+OfcM1DzdaCFTTL9jxgrnRzsPluk="
  file: msgpack-rpc-conduit-0.0.6.tar.gz
  skip_cleanup: true
  on:
    repo: TokTok/hs-msgpack-rpc-conduit
    tags: true

after_deploy:
  - mkdir -p "$HOME/.stack/upload"
  - echo "{\"username\":\"$HACKAGE_USERNAME\",\"password\":\"$HACKAGE_PASSWORD\"}" > $HOME/.stack/upload/credentials.json
  - stack --no-terminal upload .

# Only build pull requests and releases, don't build master on pushes,
# except through api or cron.
if: type IN (pull_request, api, cron) OR tag IS present
